### ISSUE TITLE
Update path for france_regions.json in examples/Notebook.ipynb

### ISSUE THREAD

**Issue by matthewfeickert** [geojupyter/jupytergis#229]
As of a4f8d8c2aa86b53d6aac232dd792997452be2b4e, in [examples/Notebook.ipynb](https://github.com/geojupyter/jupytergis/blob/a4f8d8c2aa86b53d6aac232dd792997452be2b4e/examples/Notebook.ipynb) cell 5 is

```python
doc.add_geojson_layer(path="france_regions.json")
```

however, [`france_regions.json` is at `ui-tests/tests/gis-files/`](https://github.com/geojupyter/jupytergis/blob/a4f8d8c2aa86b53d6aac232dd792997452be2b4e/ui-tests/tests/gis-files/france_regions.json) and not `examples/`.

Consider instead using `pathlib` to get the correct path for the example

```python
from pathlib import Path

doc.add_geojson_layer(path=Path().cwd().parent / "ui-tests" / "tests" / "gis-files" / "france_regions.json")
```

(assuming you're running the `examples/Notebook.ipynb` from the `examples/` directory).

**Comment by martinRenou** [comment]
Thanks for opening an issue! 

Ah it seems the file "france_regions.json" has been removed in the past from the `examples` directory because it wasn't so exciting, but the example Notebook was never updated. We should update the Notebook.

We should probably not use the one from ui-tests directory because that directory is only for testing.
