### ISSUE TITLE
COG support

### ISSUE THREAD

**Issue by martinRenou** [geojupyter/jupytergis#62]
It seems to be possible to implement GeoTIFF support with maplibre: https://leafmap.org/notebooks/92_maplibre/#cog-layer (See the [Python implementation](https://github.com/opengeos/leafmap/blob/32392eabbaa15bfd04d7f67b5e2d22f956db1bf3/leafmap/maplibregl.py#L953))

We should look into providing the same and providing UIs to create bands.

Questions to be answered:
- [ ] How does QGIS store these bands in their file? We should adopt a similar approach as them so we can get as close as possible
- [ ] Do we need to make our own deployment of https://developmentseed.org/titiler for it to work or can we simply use https://titiler.xyz ?

**Comment by vincentsarago** [comment]
Salut @martinRenou 👋 

> It seems to be possible to implement GeoTIFF support with maplibre: https://leafmap.org/notebooks/92_maplibre/#cog-layer (See the [Python implementation](https://github.com/opengeos/leafmap/blob/32392eabbaa15bfd04d7f67b5e2d22f956db1bf3/leafmap/maplibregl.py#L953))

This doesn't really implement direct COG support but rather just a way to add a TileLayer (creating tiles url dynamically for a COG Url) 

> Do we need to make our own deployment of https://developmentseed.org/titiler for it to work or can we simply use https://titiler.xyz/ ?

I guess you have 3 choices to support COG:
- direct access to COG and client side rendering (https://openlayers.org/en/latest/examples/cog.html, but Maplibre/Mapbox do not have support for this)
- using an external dynamic tile server like titiler (but not directly https://titiler.xyz/ because this is a demo endpoint, and we've kindly asking not to abuse of this endpoint, given it's fairly easy to deploy your own)
- have a dynamic tiler running alongside your application (https://github.com/banesullivan/localtileserver, https://github.com/developmentseed/rio-viz?tab=readme-ov-file#in-notebook-environment)

**Comment by martinRenou** [comment]
Thanks a lot for commenting! That's helpful. I need to educate myself with these.

> direct access to COG and client side rendering (https://openlayers.org/en/latest/examples/cog.html, but Maplibre/Mapbox do not have support for this)

Thanks! I've seen this indeed. Eventually we could allow to swap the maplibre viewer with an openlayers viewer with a plugin system. Given that there is not a library that implements all features we'd want.

> using an external dynamic tile server like titiler (but not directly https://titiler.xyz/ because this is a demo endpoint, and we've kindly asking not to abuse of this endpoint, given it's fairly easy to deploy your own)

Makes sense 👍🏽 I guess we will eventually look into deploying our own or make a tiler run next to the jupyter server somehow.

**Comment by davidbrochart** [comment]
Since `titiler` is built on FastAPI, it would be a good fit for a [jupyverse](https://github.com/jupyter-server/jupyverse) plugin. I did something similar in [xarray-leaflet](https://github.com/xarray-contrib/xarray_leaflet), the tile server is a [jupyter-server](https://github.com/jupyter-server/jupyter_server) extension so everything is served on the same domain (tiles, notebook, etc.).
Otherwise it's a bit more complicated to deploy when there are two servers.

**Comment by martinRenou** [comment]
Closing as resolved, we're using OpenLayers which does that in a server-less fashion, purely in the front-end
